project_id = "gcssanhrdnjxuwzckihk"

[functions.mp-webhook]
verify_jwt = false

[functions.send-system-email]
verify_jwt = false

[functions.check-plan-renewals]
verify_jwt = false

[functions.confirm-email]
verify_jwt = false
